name: Docker Image CI

on:
  schedule:
    - cron: '26 16 * * *'
  push:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/mariomelofilho/network-multitool:$(date +%s) --tag ghcr.io/mariomelofilho/network-multitool:latest
        docker push ghcr.io/mariomelofilho/network-multitool:latest
